### ISSUE TITLE
GitHub Pages demo

### ISSUE THREAD

**Issue by jonathantneal** [SuperOl3g/postcss-image-set-polyfill#10]
I really like your plugin!

Would you create a GitHub Pages demo? It helps people discover your plugin. I’ve created one for you, if you’d like it:

https://jonathantneal.github.io/postcss-image-set-polyfill/

You can easily copy this to your repo:

```sh
git remote add jonathantneal git@github.com:jonathantneal/postcss-image-set-polyfill.git
git fetch jonathantneal
git checkout -b fork_branch jonathantneal/gh-pages
```

**Comment by SuperOl3g** [comment]
Really thank you for your initiative!
But my plugin isn't about image-set function by itself, it's about polyfilling of this function. 
I think the target audience looking for this plugin understands what they are looking for or could understand it by description.
If they couldn't understand what does the code do without live example, they are unlikely to use this plugin in their workflow.
I'm going to add gh-page with iframe of [this](https://astexplorer.net/#/gist/86d1248cc4628f850454d3191c95efec/de5684b73276bf42df443e448b821d38f05414c4) soon. I think think it's better solution, isn't it?

**Comment by jonathantneal** [comment]
Oh, you decide what you think works best :) this was just there to help. For me, I like to immediately _play with the toy_ before I even understand how it works.
