### ISSUE TITLE
Please correct resolution size!

### ISSUE THREAD

**Issue by retyui** [SuperOl3g/postcss-image-set-polyfill#11]
### dppx: https://drafts.csswg.org/css-values-4/#dppx
This unit represents the number of dots per px unit. Due to the **1:96** fixed ratio of CSS in to CSS px, 1dppx is equivalent to 96dpi, that corresponds to the default resolution of images displayed in CSS as defined by image-resolution.

**2x** -> 2dppx -> 2 * 96dpi = **192dpi**
but youre plugin genrated 2x = 144dpi ??? 👎 

![image](https://user-images.githubusercontent.com/4661784/27011280-ff0da190-4ec0-11e7-9013-b48a00271aa0.png)

**Plese fixed it!** 😃

**Comment by SuperOl3g** [comment]
done in 75fe5563f51294ad7147ca55cc222449c0746b91

**Comment by retyui** [comment]
@SuperOl3g  Спасибо)
README файл еще бы обновить )

**Comment by SuperOl3g** [comment]
Спасибо, сделал

**Comment by retyui** [comment]
@SuperOl3g  ну еще маленькое дополнение , добавить `border-image` в эту регулярку https://github.com/SuperOl3g/postcss-image-set-polyfill/blob/master/index.js#L49 🤝
