### ISSUE TITLE
Support dppx and dpcm untits for resolution

### ISSUE THREAD

**Issue by priver** [SuperOl3g/postcss-image-set-polyfill#16]
According to the specification draft the resolution unit identifiers are: dpi, dpcm, dppx.
https://drafts.csswg.org/css-values-3/#resolution-value

But this plugin only accepts dpi units, for other units "Incorrect size value" error is thrown.

**Comment by SuperOl3g** [comment]
fixed in 03526f5242b166de156ffa5ce5940b262b3d295d
