### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by jjeising** [SuperOl3g/postcss-image-set-polyfill#17]
I'm propably missing something, but isn't support for Safari completely missing here? Safari [seems to only support device-pixel-ratio](http://caniuse.com/#feat=css-media-resolution) and the supported [`-webkit-image-set`](http://caniuse.com/#feat=css-image-set) is removed (#14).

As there is a [universal stack available](https://gist.github.com/marcedwards/3446599) shouldn't `-webkit-min-device-pixel-ratio` always be added?

**Comment by SuperOl3g** [comment]
Oops... Thanks for attentiveness!
Usually, I think most parts of users use autoprefixer which polyfill resolution media-query. So nobody noticed that there is no safari support.
Will fix this in next version

**Comment by jjeising** [comment]
> Usually, I think most parts of users use autoprefixer which polyfill resolution media-query. So nobody noticed that there is no safari support.

Absolutely right … just noticed I had disabled autoprefixer for development. Changed my configuration and the result ist as expected.

**Comment by SuperOl3g** [comment]
fixed in 98798f331f9acb2441dd00c23e45e5cd718d9221
