### ISSUE TITLE
`x` unit deprecated

### ISSUE THREAD

**Issue by strarsis** [SuperOl3g/postcss-image-set-polyfill#19]
@SuperOl3g: The `x` unit is deprecated, it should be replaced with 
https://github.com/stylelint/stylelint/issues/3026#issuecomment-345372277

(hudochenkov)
> I would recommend using dppx instead of x.

**Comment by SuperOl3g** [comment]
Sorry for waiting
I disagree that  `x` is deprecated and have described it in linked stylelint issue.
Besides this polyfill already support `dppx` units. What do you want to be done to close this issue?

**Comment by strarsis** [comment]
@SuperOl3g: I meant that the `x` unit in example in README should be replaced with `dppx` 
(so an user uses the correct alternative).

**Comment by SuperOl3g** [comment]
No, `x` unit is absolutely correct. So no changes are needed.
