### ISSUE TITLE
Output issues

### ISSUE THREAD

**Issue by strarsis** [SuperOl3g/postcss-image-set-polyfill#20]
With following input CSS
```css
background-image:
    image-set(
      url(/app/themes/the-theme/dist/10a4c3eb1294af405c55c9f4a2fe2743-4256.jpg) 1dppx
    );
````

I get the following output
```css
background-image: -webkit-image-set(url(/app/themes/the-theme/dist/10a4c3eb1294af405c55c9f4a2fe2743-4256.jpg) 1dppx);

background-image: image-set(url(/app/themes/the-theme/dist/10a4c3eb1294af405c55c9f4a2fe2743-4256.jpg) 1dppx);
````

There are no media queries based polyfills generated by the plugin.

**Comment by SuperOl3g** [comment]
There are no images for other resolution.
What is the correct result in your opinion and why?

**Comment by strarsis** [comment]
You are right of course, there are no other densities, so there is no reason for `@media` queries (and it works correctly with densities other than the default 1dppx, see https://astexplorer.net/#/gist/a5feff399b3fad565f5fb3dc966cec26/cc641c418b4b958105e2c064f09c596acf46a49b).
