### ISSUE TITLE
Upgrade to postcss 6.x

### ISSUE THREAD

**Issue by Semigradsky** [SuperOl3g/postcss-image-set-polyfill#6]
This requires a major version bump.

[PostCSS Changelog](https://github.com/postcss/postcss/blob/master/CHANGELOG.md#60-marquis-orias)

**Comment by SuperOl3g** [comment]
Done in 77ddf04fac0286c1557ca5df024c06f085603084

**Comment by SuperOl3g** [comment]
@Semigradsky, maybe you know why nobody add `PostCSS` as peer dependency for their plugins?

**Comment by jonathantneal** [comment]
Thanks for doing this, @SuperOl3g! I think you can close this issue then.

FWIW, I think `peerDependencies` are not used because they are no longer installed by default in npm3+. See https://docs.npmjs.com/files/package.json#peerdependencies
