### ISSUE TITLE
ES5 vs ES6

### ISSUE THREAD

**Issue by jonathantneal** [SuperOl3g/postcss-image-set-polyfill#9]
PostCSS v6 is for Node 4+, but I see you [rolled back to ES5](https://github.com/SuperOl3g/postcss-image-set-polyfill/commit/4c65a0b7330f4dd75eba64214555a9f360d6cc62). What was the issue?

I’m not sure your plugin will remain Node 0.12 compatible in the PostCSS ecosystem.

**Comment by SuperOl3g** [comment]
Because of my plugin is a part of [`postcss-cssnext`](https://github.com/MoOx/postcss-cssnext)
Its CI tests requires Node 0.12 compatibility.
@Semigradsky, are we already must support such old versions?

**Comment by Semigradsky** [comment]
cssnext has dropped Node 0.12 support too

**Comment by SuperOl3g** [comment]
@Semigradsky I could move to ES6 only when you remove Node 0.12 from [`.travis.yml`](https://github.com/MoOx/postcss-cssnext/blob/master/.travis.yml) at master branch.

**Comment by SuperOl3g** [comment]
fixed in 0d07d77861aa8dbbc7af7478239b7c28a9e632a5
